/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as EmployeeTasksRouteImport } from './routes/employee.tasks'
import { Route as EmployeeProfileRouteImport } from './routes/employee.profile'
import { Route as EmployeeLmsRouteImport } from './routes/employee.lms'
import { Route as EmployeeLeaveRouteImport } from './routes/employee.leave'
import { Route as EmployeeFeedbackRouteImport } from './routes/employee.feedback'
import { Route as EmployeeDirectoryRouteImport } from './routes/employee.directory'
import { Route as DashboardWorkRouteImport } from './routes/dashboard.work'
import { Route as DashboardTalentRouteImport } from './routes/dashboard.talent'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardPoliciesRouteImport } from './routes/dashboard.policies'
import { Route as DashboardOrgRouteImport } from './routes/dashboard.org'
import { Route as DashboardOnboardingRouteImport } from './routes/dashboard.onboarding'
import { Route as DashboardMonitorRouteImport } from './routes/dashboard.monitor'
import { Route as DashboardLmsRouteImport } from './routes/dashboard.lms'
import { Route as DashboardLeaveRouteImport } from './routes/dashboard.leave'
import { Route as DashboardHrmRouteImport } from './routes/dashboard.hrm'
import { Route as DashboardEvaluationsRouteImport } from './routes/dashboard.evaluations'
import { Route as DashboardErpRouteImport } from './routes/dashboard.erp'
import { Route as DashboardCrmRouteImport } from './routes/dashboard.crm'

const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const EmployeeTasksRoute = EmployeeTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeLmsRoute = EmployeeLmsRouteImport.update({
  id: '/lms',
  path: '/lms',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeLeaveRoute = EmployeeLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeFeedbackRoute = EmployeeFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeDirectoryRoute = EmployeeDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => EmployeeRoute,
} as any)
const DashboardWorkRoute = DashboardWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTalentRoute = DashboardTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPoliciesRoute = DashboardPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrgRoute = DashboardOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitorRoute = DashboardMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLmsRoute = DashboardLmsRouteImport.update({
  id: '/lms',
  path: '/lms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeaveRoute = DashboardLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHrmRoute = DashboardHrmRouteImport.update({
  id: '/hrm',
  path: '/hrm',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEvaluationsRoute = DashboardEvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardErpRoute = DashboardErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCrmRoute = DashboardCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/erp': typeof DashboardErpRoute
  '/dashboard/evaluations': typeof DashboardEvaluationsRoute
  '/dashboard/hrm': typeof DashboardHrmRoute
  '/dashboard/leave': typeof DashboardLeaveRoute
  '/dashboard/lms': typeof DashboardLmsRoute
  '/dashboard/monitor': typeof DashboardMonitorRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/org': typeof DashboardOrgRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/talent': typeof DashboardTalentRoute
  '/dashboard/work': typeof DashboardWorkRoute
  '/employee/directory': typeof EmployeeDirectoryRoute
  '/employee/feedback': typeof EmployeeFeedbackRoute
  '/employee/leave': typeof EmployeeLeaveRoute
  '/employee/lms': typeof EmployeeLmsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/employee/': typeof EmployeeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/erp': typeof DashboardErpRoute
  '/dashboard/evaluations': typeof DashboardEvaluationsRoute
  '/dashboard/hrm': typeof DashboardHrmRoute
  '/dashboard/leave': typeof DashboardLeaveRoute
  '/dashboard/lms': typeof DashboardLmsRoute
  '/dashboard/monitor': typeof DashboardMonitorRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/org': typeof DashboardOrgRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/talent': typeof DashboardTalentRoute
  '/dashboard/work': typeof DashboardWorkRoute
  '/employee/directory': typeof EmployeeDirectoryRoute
  '/employee/feedback': typeof EmployeeFeedbackRoute
  '/employee/leave': typeof EmployeeLeaveRoute
  '/employee/lms': typeof EmployeeLmsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/dashboard': typeof DashboardIndexRoute
  '/employee': typeof EmployeeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/erp': typeof DashboardErpRoute
  '/dashboard/evaluations': typeof DashboardEvaluationsRoute
  '/dashboard/hrm': typeof DashboardHrmRoute
  '/dashboard/leave': typeof DashboardLeaveRoute
  '/dashboard/lms': typeof DashboardLmsRoute
  '/dashboard/monitor': typeof DashboardMonitorRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/org': typeof DashboardOrgRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/talent': typeof DashboardTalentRoute
  '/dashboard/work': typeof DashboardWorkRoute
  '/employee/directory': typeof EmployeeDirectoryRoute
  '/employee/feedback': typeof EmployeeFeedbackRoute
  '/employee/leave': typeof EmployeeLeaveRoute
  '/employee/lms': typeof EmployeeLmsRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/employee/': typeof EmployeeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/employee'
    | '/dashboard/crm'
    | '/dashboard/erp'
    | '/dashboard/evaluations'
    | '/dashboard/hrm'
    | '/dashboard/leave'
    | '/dashboard/lms'
    | '/dashboard/monitor'
    | '/dashboard/onboarding'
    | '/dashboard/org'
    | '/dashboard/policies'
    | '/dashboard/reports'
    | '/dashboard/talent'
    | '/dashboard/work'
    | '/employee/directory'
    | '/employee/feedback'
    | '/employee/leave'
    | '/employee/lms'
    | '/employee/profile'
    | '/employee/tasks'
    | '/dashboard/'
    | '/employee/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/crm'
    | '/dashboard/erp'
    | '/dashboard/evaluations'
    | '/dashboard/hrm'
    | '/dashboard/leave'
    | '/dashboard/lms'
    | '/dashboard/monitor'
    | '/dashboard/onboarding'
    | '/dashboard/org'
    | '/dashboard/policies'
    | '/dashboard/reports'
    | '/dashboard/talent'
    | '/dashboard/work'
    | '/employee/directory'
    | '/employee/feedback'
    | '/employee/leave'
    | '/employee/lms'
    | '/employee/profile'
    | '/employee/tasks'
    | '/dashboard'
    | '/employee'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/employee'
    | '/dashboard/crm'
    | '/dashboard/erp'
    | '/dashboard/evaluations'
    | '/dashboard/hrm'
    | '/dashboard/leave'
    | '/dashboard/lms'
    | '/dashboard/monitor'
    | '/dashboard/onboarding'
    | '/dashboard/org'
    | '/dashboard/policies'
    | '/dashboard/reports'
    | '/dashboard/talent'
    | '/dashboard/work'
    | '/employee/directory'
    | '/employee/feedback'
    | '/employee/leave'
    | '/employee/lms'
    | '/employee/profile'
    | '/employee/tasks'
    | '/dashboard/'
    | '/employee/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/employee/tasks': {
      id: '/employee/tasks'
      path: '/tasks'
      fullPath: '/employee/tasks'
      preLoaderRoute: typeof EmployeeTasksRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/lms': {
      id: '/employee/lms'
      path: '/lms'
      fullPath: '/employee/lms'
      preLoaderRoute: typeof EmployeeLmsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/leave': {
      id: '/employee/leave'
      path: '/leave'
      fullPath: '/employee/leave'
      preLoaderRoute: typeof EmployeeLeaveRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/feedback': {
      id: '/employee/feedback'
      path: '/feedback'
      fullPath: '/employee/feedback'
      preLoaderRoute: typeof EmployeeFeedbackRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/directory': {
      id: '/employee/directory'
      path: '/directory'
      fullPath: '/employee/directory'
      preLoaderRoute: typeof EmployeeDirectoryRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/dashboard/work': {
      id: '/dashboard/work'
      path: '/work'
      fullPath: '/dashboard/work'
      preLoaderRoute: typeof DashboardWorkRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/talent': {
      id: '/dashboard/talent'
      path: '/talent'
      fullPath: '/dashboard/talent'
      preLoaderRoute: typeof DashboardTalentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/policies': {
      id: '/dashboard/policies'
      path: '/policies'
      fullPath: '/dashboard/policies'
      preLoaderRoute: typeof DashboardPoliciesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/org': {
      id: '/dashboard/org'
      path: '/org'
      fullPath: '/dashboard/org'
      preLoaderRoute: typeof DashboardOrgRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/onboarding': {
      id: '/dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitor': {
      id: '/dashboard/monitor'
      path: '/monitor'
      fullPath: '/dashboard/monitor'
      preLoaderRoute: typeof DashboardMonitorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lms': {
      id: '/dashboard/lms'
      path: '/lms'
      fullPath: '/dashboard/lms'
      preLoaderRoute: typeof DashboardLmsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leave': {
      id: '/dashboard/leave'
      path: '/leave'
      fullPath: '/dashboard/leave'
      preLoaderRoute: typeof DashboardLeaveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hrm': {
      id: '/dashboard/hrm'
      path: '/hrm'
      fullPath: '/dashboard/hrm'
      preLoaderRoute: typeof DashboardHrmRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/evaluations': {
      id: '/dashboard/evaluations'
      path: '/evaluations'
      fullPath: '/dashboard/evaluations'
      preLoaderRoute: typeof DashboardEvaluationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/erp': {
      id: '/dashboard/erp'
      path: '/erp'
      fullPath: '/dashboard/erp'
      preLoaderRoute: typeof DashboardErpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crm': {
      id: '/dashboard/crm'
      path: '/crm'
      fullPath: '/dashboard/crm'
      preLoaderRoute: typeof DashboardCrmRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCrmRoute: typeof DashboardCrmRoute
  DashboardErpRoute: typeof DashboardErpRoute
  DashboardEvaluationsRoute: typeof DashboardEvaluationsRoute
  DashboardHrmRoute: typeof DashboardHrmRoute
  DashboardLeaveRoute: typeof DashboardLeaveRoute
  DashboardLmsRoute: typeof DashboardLmsRoute
  DashboardMonitorRoute: typeof DashboardMonitorRoute
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardOrgRoute: typeof DashboardOrgRoute
  DashboardPoliciesRoute: typeof DashboardPoliciesRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardTalentRoute: typeof DashboardTalentRoute
  DashboardWorkRoute: typeof DashboardWorkRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCrmRoute: DashboardCrmRoute,
  DashboardErpRoute: DashboardErpRoute,
  DashboardEvaluationsRoute: DashboardEvaluationsRoute,
  DashboardHrmRoute: DashboardHrmRoute,
  DashboardLeaveRoute: DashboardLeaveRoute,
  DashboardLmsRoute: DashboardLmsRoute,
  DashboardMonitorRoute: DashboardMonitorRoute,
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardOrgRoute: DashboardOrgRoute,
  DashboardPoliciesRoute: DashboardPoliciesRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardTalentRoute: DashboardTalentRoute,
  DashboardWorkRoute: DashboardWorkRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EmployeeRouteChildren {
  EmployeeDirectoryRoute: typeof EmployeeDirectoryRoute
  EmployeeFeedbackRoute: typeof EmployeeFeedbackRoute
  EmployeeLeaveRoute: typeof EmployeeLeaveRoute
  EmployeeLmsRoute: typeof EmployeeLmsRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeTasksRoute: typeof EmployeeTasksRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeDirectoryRoute: EmployeeDirectoryRoute,
  EmployeeFeedbackRoute: EmployeeFeedbackRoute,
  EmployeeLeaveRoute: EmployeeLeaveRoute,
  EmployeeLmsRoute: EmployeeLmsRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeTasksRoute: EmployeeTasksRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
